### ISSUE TITLE
PREVIEW: Markup and Option Boxes Bug

### ISSUE THREAD

**Issue by mymercurialsky** [buildcom/BossyUI#161]
There appears to be a bug in the preview sandbox where the markup and option boxes are behaving strangely. The line your cursor is on isn't lining up with the text when you try to make changes. This began last week after we pulled the upstream repo.

**Comment by glawson** [comment]
Thanks @mymercurialsky, I'll take a look.

**Comment by glawson** [comment]
whole preview was replaced with 'site'
