### ISSUE TITLE
TOOLTIP: Tooltip's positions can cover text or have an awkward position.

### ISSUE THREAD

**Issue by tabersays** [buildcom/BossyUI#243]
Text is completely covered:
![image](https://cloud.githubusercontent.com/assets/6550773/12628488/4d93faca-c4f8-11e5-8f18-2495f6ef88eb.png)
![image](https://cloud.githubusercontent.com/assets/6550773/12628528/71207f36-c4f8-11e5-9d9b-cd5aada05267.png)

**Comment by tmjam** [comment]
Duplicated and elaborated in #285
