### ISSUE TITLE
NAVIGATION: Sub-menu containers need fixed spacing, alignment

### ISSUE THREAD

**Issue by kbuffardi** [buildcom/BossyUI#248]
Currently, there is a vertical gap between the top level menu and the sub-menu container boxes. They should be attached so it is clear which sub-menu is being displayed. They should not be offset horizontally either.

**Comment by rahulhgaikwad** [comment]
This issue has been fixed #245 
I will work of the remaining part regarding this issue which is changing the color scheme of menus and text.

**Comment by kbuffardi** [comment]
Old issue, will be addressed in new UX design
