### ISSUE TITLE
AUTOCOMPLETE: Auto complete does not search strings between the words.

### ISSUE THREAD

**Issue by tmjam** [buildcom/BossyUI#249]

**Comment by ebracho** [comment]
Can you give an example?

**Comment by kbuffardi** [comment]
Match shouldn't just be at the beginning of a string, e.g.:

"pples" should match with "apples"

**Comment by ebracho** [comment]
> "pples" should match with "apples"
That is the current behavior. As long as the query is within the specified number of corrections of an item in the dictionary, it will match.

![autocmplete_demo](https://cloud.githubusercontent.com/assets/2525276/14330350/0f1cb2a8-fbf5-11e5-8660-0347069480b3.PNG)

See it here: http://ebracho.github.io/AutocompleteDemo/

**Comment by tmjam** [comment]
<img width="489" alt="screenshot 2016-04-06 12 45 55" src="https://cloud.githubusercontent.com/assets/964223/14330481/a0d975b4-fbf5-11e5-9e6f-d5ac57caccf8.png">

**Comment by kbuffardi** [comment]
Yeah, as @tmjam showed, it is not completing "alabama" if "bama" is typed and likewise if you type "jersey" it is not recommending "new jersey"

**Comment by ebracho** [comment]
Yes, the correction match algorithm matches strictly on [edit distance](https://en.wikipedia.org/wiki/Edit_distance) of strings (not words). 

It shouldn't be too difficult to alter the matching algorithm to match against separated words within the strings.

Here's a new idea for a feature: allow the users to provide a set of keys for each entry in the dictionary. For example, if an entry is "California State University Chico", the user could add keys like "Chico", "CSU Chico", "Chico State", etc.
