### ISSUE TITLE
DOCUMENTATION - Environment setup guide 

### ISSUE THREAD

**Issue by lcheung90** [buildcom/BossyUI#251]
As a newcomer to this project, I ran into a couple issues when trying to set up the development environment as described by the contributing guide.

Running `bower install` at the root of the project, I got the following error:
`bower ENOENT        No bower.json present` 
The fix was to run 'bower install` inside the site directory.

The other issue occurred when trying to run `gulp site`

>/bin/sh: 1: nodemon: not found
>[17:22:38] 'site-serve' errored after 10 ms
>[17:22:38] Error in plugin 'gulp-shell'
>Message:
>   Command failed: /bin/sh -c nodemon site/server.js
>/bin/sh: 1: nodemon: not found
>
>Details:
>   killed: false
>   code: 127
>   signal: null
>   cmd: /bin/sh -c nodemon site/server.js
>   stdout: 
>   stderr: /bin/sh: 1: nodemon: not found
>
>[17:22:38] 'site' errored after 982 ms
>[17:22:38] Error in plugin 'run-sequence
>Message:
>   An error occured in task 'site-serve'.

My workaround was to run `node site.js` inside the site directory. Although the sandbox loads, I am certain it is not correct to bypass all the tasks.

I would like to update the guide once I figure out how to fix the last issue. #dibs

**Comment by radfahrer** [comment]
You will need to have nodemon installed globally `npm install -g nodemon`. Perhaps we could trigger this as part of a post install script as mentioned in the following article: http://www.sitepoint.com/solve-global-npm-module-dependency-problem we could also put the bower install in our post install script.

**Comment by glawson** [comment]
Yes, let's get that into the issues list.  Should be a quick fix.

Geoff Lawson
Front-End Software Architect
------------------------------
Build.com, Inc.
Smarter Home Improvement™
P: 800.375.3403

**Comment by lcheung90** [comment]
@radfahrer `npm install -g nodemon` seemed to do the trick. I will update the environment setup docs ASAP.
