### ISSUE TITLE
ToolTip: Position of the Tooltip is misplaced

### ISSUE THREAD

**Issue by SatyajeetSwamy** [buildcom/BossyUI#285]
$scope.config.align = "center";
// Tooltip position in relation to element; Top, right, bottom, left.
$scope.config.position = "bottom";
// Text color.
$scope.config.color = "blue";
// Tooltip base types; Default, download.
$scope.config.type = "download";

With these changes the tooltip is displayed on the text, rather than showing it on the bottom as mentioned above!

**Comment by priteshjagani** [comment]
This issue is same as #243 issue. 
I think we should close one of these. And I have fixed it, and will create a pull request by tonight.
