### ISSUE TITLE
TOOLTIP: Arrow is not positioned exactly at the center for 'top' and 'bottom' positions

### ISSUE THREAD

**Issue by kapiljituri** [buildcom/BossyUI#292]
If we set progress to 50%, we can see arrow of tooltip positioned slightly to the left of exact midpoint.
![screenshot-4](https://cloud.githubusercontent.com/assets/10738856/14335744/8481e7da-fc12-11e5-92d7-59835e39d740.png)

**Comment by radfahrer** [comment]
resolved by TOOLTIP-292
