### ISSUE TITLE
Graph X-Y plane alignment

### ISSUE THREAD

**Issue by tpatil2** [buildcom/BossyUI#300]
If we give input widthe and height more than 500 and 550 respectively,
Then it graph goes beyond visible area of window

// Graph height in pixels.
$scope.config.height = 550;
// Graph width in pixels.
$scope.config.width = 500;
// Label for x-axis.

**Comment by priteshjagani** [comment]
I tried but it doesn't happen in my computer. can you share a screenshot!
<img width="1440" alt="screen shot 2016-05-02 at 3 42 19 pm" src="https://cloud.githubusercontent.com/assets/8827617/14970279/8a5d29fc-107c-11e6-989d-f297054fd253.png">

**Comment by tpatil2** [comment]
Thats the maximum limit...try any value more than that 500 and 550
