### ISSUE TITLE
Site Refresh

### ISSUE THREAD

**Issue by radfahrer** [buildcom/BossyUI#316]
Use new mocks to update the site.

**Comment by radfahrer** [comment]
@glawson actually still working on this

**Comment by carlyculver** [comment]
COLORS:

Green (light): #4bc47d (SASS 30% dark tint for darker green)
Blue (light): #75afd3
Side Bar "Black": #111416
Navy Blue: #011524

That should be all the colors, besides white of course.

**Comment by carlyculver** [comment]
Students who have contributed to BossyUI between Fall 2014-Spring 2016 (alphabetical by last name):

Colin Baldwin
Patrick Barnum
Eddie Bracho
Edward Brown
Thomas Carrel
Luis Cheung
James Crean
Manuel De La Rosa
Sumit Dorle
Lukas Fink
Taber Fitzgerald
Rahul Gaikwad
Rogelio Garay-Morfin
Alexandre Garcez Nunes
Tyler Gering
Sean German
Michael Gonsalves
Thibaut Hardin
Pritesh Jagani
Shirley Jin
Kapi Jituri
Cory Lotze
Gabriel Mabalot
Alen Maragoul
Shelby Martin
Austin Matthews
Seth McFarland
Erik Mellum
Martin Mojica
Tejas Patil
Adam Penn
Evan Roberts
Jordan Salvagno
Alberto Sarmienta
Pedro Sobral
Michael Spencer
Rick Stone
Satyajeet Swamy
Francisco Tadillo
Rushi Thakkar
James Thayer
Chue Vang
Phanat Xiong

**Comment by carlyculver** [comment]
![bossyio_aboutpg](https://cloud.githubusercontent.com/assets/9680803/22434935/f6fa1a66-e6d2-11e6-8025-848f913febcb.png)
![bossyui_logo](https://cloud.githubusercontent.com/assets/9680803/22434936/f6faf4d6-e6d2-11e6-90ff-9c56f21926a0.png)

![website_may10](https://cloud.githubusercontent.com/assets/9680803/22434950/00f60e30-e6d3-11e6-8c55-a32a94ad3bdc.png)
