### ISSUE TITLE
Research building filters in Angular

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#515]
Should assign 3 team members.

1.  Figure out how to build an Angular filter.
2.  Figure out how to use filters in a ngFor.
3.  Figure out how to use filters to change user input. 
4. Create a code example of a filter that implements 2 and 3, upload to a github gist.  (do not copy the Angular doc example)
5. Add gist link (url) to issue as issue comment, per member.

**Comment by ClassicSours** [comment]
https://gist.github.com/ClassicSours/c5bfdf3c975bc02e58fd0267532a7152

I'll show a demo of my code during the monday standup

**Comment by Mriewer** [comment]
https://gist.github.com/Mriewer/18772357fd4c7288ef21b3328b944b58#file-app-names-pipe-ts

This was the file I was working on to segment names from <first> <last>(any format) to <First> <last initial>
