### ISSUE TITLE
Research validation libraries for JS

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#516]
Should assign 3 team members.

1.  Google / search for existing JS libraries that validate object data.  Ie: that the variable is a string, and has a value, and has a mix of numbers and characters, and objects.
2.  Assure the libraries are installable via npm.
3.  Determine the size of the lib when loaded.
4.  Create an example component that uses the lib to validate a value.  Is might be a good candidate for a unit test.  Create a github gist to show your example.

**Comment by oliverrayreed** [comment]
https://gist.github.com/oliverrayreed/6e3f198e338f4112b8e30f1de815cd55

**Comment by Cjoseph4** [comment]
https://gist.github.com/Cjoseph4/7afaf2fbf61b205ab053bcf2367930a1

**Comment by matthewsamuel95** [comment]
https://gist.github.com/matthewsamuel95/df18119537e4aed676c15306c336ccd4

**Comment by oliverrayreed** [comment]
Are we not interested in using the validations built into AngularJS? https://github.com/angular/angular/blob/4.4.5/packages/forms/src/validators.ts#L30-L29

**Comment by glawson** [comment]
@oliverrayreed - sure we are, present this to us on Monday :)
