### ISSUE TITLE
Update Form Config

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#527]
The current form config needs an interface and needs other properties to aline with Bootstrap options found at https://getbootstrap.com/docs/4.0/components/forms/#layout.  It also needs attribute(s) that would hook it into data and or a Service (see: https://angular.io/tutorial/toh-pt4)

**Comment by Mriewer** [comment]
https://gist.github.com/Mriewer/560898dba59279ef80a4acb0db90621c#file-update-form-config-527

**Comment by Mriewer** [comment]
https://gist.github.com/Mriewer/514cf1a6dd9214746599cd10a88191ed

**Comment by glawson** [comment]
@Mriewer - make a pull request.
