### ISSUE TITLE
Create Form Constants Service

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#529]
Create a service that holds all constant types for Form and related components.

**Comment by oliverrayreed** [comment]
https://gist.github.com/oliverrayreed/a52bc0b94ef96c3de01e1edc4820f125

is this even close?

**Comment by oliverrayreed** [comment]
what about this, is this what I am shooting for?

https://gist.github.com/oliverrayreed/0ef091b857f27cb007edb9a3f6406baf

**Comment by glawson** [comment]
@oliverrayreed  - yes, but since it's a string const you will use uppercase for both the variable and value.
