### ISSUE TITLE
Reto Notes

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#540]

**Comment by glawson** [comment]
@tabersays - please add your notes

**Comment by tabersays** [comment]
**What went well:**
- Practice working with foriegn code
- Responsive chat questions

**What went badly:**
- Documentation: How do we use the widgets
- Reading files understanding structure

**Comments:**
- What can we do differently to handle chanlleges:
-- Start earlier/investigate problem
-- Ask questions/What can we ask
