### ISSUE TITLE
Increase display size of 'config' field for sandbox components.

### ISSUE THREAD

**Issue by glawson** [buildcom/BossyUI#541]

**Comment by ClassicSours** [comment]
I was wondering if you could expand on what you mean by "increase display size"  
Are you trying to get 'form' to fill the entire height of its component output?  
Should the font be increased? 
Should each each ace_editor be different sizes to accommodate their output or should they all be the same size?

**Comment by glawson** [comment]
@ClassicSours; right now the ace editor takes up 1/2 of the content area.  I would like the width to double, full content area.  And we could put the output below each editor.  Each editor should be the same size.  We might also explore popping each component into it's own window??
